version: 1.0.{build}
os: Visual Studio 2017

environment:
    COVERALLS_REPO_TOKEN:  
       secure: lGGIj3WmsCghU2af2Y3pzOeViNSEv2MeV24znk/Jjx0mT7S+d+uv6sS5ziCylvKT
    SONARQUBE_TOKEN:
       secure: /H4KJSrixYtM+HjJ/gCb9QogeN6WmmvdlsUQby/BVISc44V1EcZ078ZydkwMC+ep

install:
    - nuget restore

build_script:
    - choco install "msbuild-sonarqube-runner" -y
    - MSBuild.SonarQube.Runner.exe begin /k:"Cdfs" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=%SONARQUBE_TOKEN%" /d:"sonar.organization=drcjt-github"
    - msbuild "Cdfs.sln" /verbosity:normal
    - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=%SONARQUBE_TOKEN%"

test_script:
    - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]* -[*Tests]* -[Moq*]*" -target:"nunit3-console.exe" -targetargs:"/domain:single /result:myresults.xml;format=AppVeyor .\Tests\NameNodeTests\bin\debug\NameNodeTests.dll .\Tests\DataNodeTests\bin\debug\DataNodeTests.dll .\Tests\DFSClientTests\bin\debug\DFSClientTests.dll" -output:coverage.xml -returntargetcode

after_test: 
    - packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml