version: 1.0.{build}
os: Visual Studio 2017

environment:
    COVERALLS_REPO_TOKEN:  
       secure: lGGIj3WmsCghU2af2Y3pzOeViNSEv2MeV24znk/Jjx0mT7S+d+uv6sS5ziCylvKT

install:
    - nuget restore

build_script:
    - choco install "msbuild-sonarqube-runner" -y
    - MSBuild.SonarQube.Runner.exe begin /k:"Cdfs" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=4f25726209d441b4d8223ac458fdb72d5710c7ed"
    - msbuild "Cdfs.sln" /verbosity:normal
    - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=4f25726209d441b4d8223ac458fdb72d5710c7ed" /d:"sonar.exclusions=**/*.html"

test_script:
    - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"nunit3-console.exe" -targetargs:"/domain:single /result:myresults.xml;format=AppVeyor tests\bin\debug\CdfsTests.dll" -output:coverage.xml -returntargetcode

after_test: 
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml