version: 1.0.{build}
os: Visual Studio 2017

environment:
    COVERALLS_REPO_TOKEN:  
       secure: lGGIj3WmsCghU2af2Y3pzOeViNSEv2MeV24znk/Jjx0mT7S+d+uv6sS5ziCylvKT
    SONARQUBE_TOKEN:
       secure: /H4KJSrixYtM+HjJ/gCb9QogeN6WmmvdlsUQby/BVISc44V1EcZ078ZydkwMC+ep

install:
    - nuget restore
    
build_script:
    - msbuild "Cdfs.sln" /verbosity:normal
    
test_script:
   - c:\users\appveyor\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe -oldStyle -register:user -filter:"+[*]* -[*Tests*]* -[Moq*]*" -target:"dotnet.exe" -targetargs:"test /p:DebugType=full ./Tests/NameNodeTests\NameNodeTests.csproj" -output:coverage.xml -returntargetcode -mergeoutput
   - c:\users\appveyor\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe -oldStyle -register:user -filter:"+[*]* -[*Tests*]* -[Moq*]*" -target:"dotnet.exe" -targetargs:"test /p:DebugType=full ./Tests/DataNodeTests\DataNodeTests.csproj" -output:coverage.xml -returntargetcode -mergeoutput
   - c:\users\appveyor\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe -oldStyle -register:user -filter:"+[*]* -[*Tests*]* -[Moq*]*" -target:"dotnet.exe" -targetargs:"test /p:DebugType=full ./Tests/DFSClientTests\DFSClientTests.csproj" -output:coverage.xml -returntargetcode -mergeoutput
    
after_test: 
    # Upload coverage to coveralls
    - c:\users\appveyor\.nuget\packages\coveralls.io\1.4.2\tools\coveralls.net.exe --opencover coverage.xml

    # Run sonarqube
    - choco install "msbuild-sonarqube-runner" -y
    - MSBuild.SonarQube.Runner.exe begin /k:"Cdfs" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=%SONARQUBE_TOKEN%" /d:"sonar.organization=drcjt-github" /d:"sonar.exclusions=**/*.js" /d:"sonar.cs.opencover.reportsPath=coverage.xml"
    - msbuild "Cdfs.sln" /verbosity:normal
    - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=%SONARQUBE_TOKEN%"